# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62d97088bb875846139a22e0100b37bdcaea38e1c4b584fada0157ba393c47cc5267068f613e887bce3d7867a4608d85b12b3ef393c72b041b516eaef14d4f81

test:
  secret_key_base: a00f8da08b02cecc34d712a718e4fb940ad81afa2c79a4f69a6c3130afbadc5373d8410bb88b9c126adeb4c80387561c6ecc19a15d9a34736af6094ffc93b986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
